### ISSUE TITLE
ferret - disable option

### ISSUE THREAD

**Issue by skandlab** [skandlab/mirmaid#3]
lettere og hurtigere install og data-load. Hvorfor i al verden tager ferret så lang tid om at indexere?

Hmmm. HAr nu ventet 5 minutter på at der skal ske noget efter at have trykket på precursor-knappen. ....nu blev den færdig - meget lang log med nogle mærkelige beskeder om index-ting. Må være ferret. Håber at det er noget der gemmes på disk, så den virker hurtigere næste gang jeg starter en development-server. Kører det mon hurtigere i production mode?
- Det tager lang tid at indexere første gang (rake load). Tingene i loggen er ikke fejl, bare info. Logning burde være disablet i produktions mode - det skal vi have tjekket op på. Jeg ved ikke helt hvorfor det delay kommer FØRSTE gang web interface bruges EFTER load (mener også jeg har oplevet det en enkelt gang).
- Og ja, indexeringen gemmes på disk. Jeg oplever aldrig ventetid.
- Ferret kan disables. Det kræver bare et tjek i controller koden. I Lite udgaven bør ferret være disabled.

**Comment by mortenlindow** [comment]
ok - så længe det er en first time thing gør det vel ikke så meget.

**Comment by skandlab** [comment]
This is now fixed.
1) Ferret can now be disbled in the 'config/mirmaid_config.yml' (still need to be installed though)
2) The initial indexing is much faster with the current ferret version 0.4.4.
